import { Suspense } from 'react';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { FloatingCart } from '@/components/cart/floating-cart';
import { Toaster } from '@/components/ui/sonner';
import type { Metadata } from 'next';
import { Inter, JetBrains_Mono } from 'next/font/google';
import 'swiper/css';

import './globals.css';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
});

const jetbrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: {
    googleBot: {
      index: false,
      follow: false,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} font-sans antialiased`}
        suppressHydrationWarning
      >
        <NuqsAdapter>
          {children}
          <Suspense fallback={null}>
            <FloatingCart />
          </Suspense>
          <Toaster richColors />
        </NuqsAdapter>
      </body>
    </html>
  );
}
